### ISSUE TITLE
Carrying classes and ID's forward to the IMG tag

### ISSUE THREAD

**Issue by andrewminton** [firegoby/Imager.js#3]
Is there scope to persist the original attributes of the div such as ID's and Classes over to the image?

I have classes on the div generated by the ninja technique and they get wiped out by imager. It would be ideal if imager did not interfere with this markup and leave id's and classes apart from the selector used to target imager in the first place. make sense?

The `this.divs` object also needs to cater for differing classes on each item in the array. Which I'm guessing it can't currently do. Not 100% sure though.

**Comment by firegoby** [comment]
This **only** copies over the ID and Class attributes (not any custom attributes like `data-x`, not sure how best to handle that without more thought). Also this is only lightly tested on my test suite so if you run into any weird behaviour please let me know, thanks.

edit: Oh - and could you expand on the `this.divs` issue, wasn't quite sure what needs addressing, thx

**Comment by andrewminton** [comment]
Cool beans!

The 'this.divs' thing was me not understanding how the configuration options we're built. so ignore that one :)
