### ISSUE TITLE
Alt attribut

### ISSUE THREAD

**Issue by yoyurec** [firegoby/Imager.js#4]
In original Imager.js was usefull **data-alt** attribute, which deleted on your fork ((
How can i output alt text for images? I't important for SEO...

**Comment by firegoby** [comment]
I haven't got time to test this today, or push an actual update, but this should do it...

Add just after Line #139 in `Imager.js`

```
if (divs[i].hasAttribute('data-alt')) {
    gif.alt = divs[i].getAttribute('data-alt');
}
```

Hope it works, let me know, thanks

**Comment by yoyurec** [comment]
i did it bymyself )
it works
