### ISSUE TITLE
Missing alt tag in imager.xsl

### ISSUE THREAD

**Issue by wdebusschere** [firegoby/Imager.js#5]
Alt tag on images: data-alt="{$alt}"

   <div class="{$class}" data-src="{$jit}{$image/@path}/{$image/filename}" data-width="{$width}" data-alt="{$alt}">

**Comment by andrewminton** [comment]
Did you manage to get this working at all?

Keen to know if it's been implemented by anyone yet.

**Comment by firegoby** [comment]
Sorry, completely forgot about this, my bad :) 

Just had a look at this for you, you can enable alt text support with two edits...

Add as new line 135 (i.e. after 134) to `Imager.js`: -
    `gif.setAttribute('alt', divs[i].getAttribute('data-alt'));`

And if you're using `imager.xsl` to generate your markup, change line 10 to: -
    `<div class="{$class}" data-src="{$jit}{$image/@path}/{$image/filename}" data-width="{$width}" data-alt="{$alt}">`

(i.e. just add the `data-alt={$alt}` bit to the end of the element)

To use just add a `data-alt` attribute to your placeholder markup and that will be applied to the replaced image.

Explanation: The first edit makes sure Imager will copy over the alt text from the placeholder markup to the replaced image markup, and the second will copy the alt text onto the placeholder that's generated via XSLT

If you do have any problems just let me know

**Comment by andrewminton** [comment]
Superb! Thanks @firegoby :)
